# Generated by Django 5.1.2 on 2024-11-03 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='industrys',
            new_name='industry',
        ),
    ]
